import { NodeForceRule, EdgeForceRule, CallEdge, UsesEdge } from './types';

export const defaultNodeRules: NodeForceRule[] = [
  {
    id: 'function-nodes',
    label: 'Functions',
    enabled: true,
    match: (n) => n.kind === 'FUNCTION',
    forces: { charge: -100, collideRadius: 8 },
    style: { color: '#10b981', radius: 5 },
  },
  {
    id: 'class-nodes',
    label: 'Classes',
    enabled: true,
    match: (n) => n.kind === 'CLASS',
    forces: { charge: -300, collideRadius: 20 },
    style: { color: '#f59e0b', radius: 10 },
  },
  {
    id: 'interface-nodes',
    label: 'Interfaces',
    enabled: true,
    match: (n) => n.kind === 'INTERFACE',
    forces: { charge: -150, collideRadius: 12 },
    style: { color: '#8b5cf6', radius: 7 },
  },
  {
    id: 'import-nodes',
    label: 'Imports',
    enabled: true,
    match: (n) => n.kind === 'IMPORT',
    forces: { charge: -80, collideRadius: 6 },
    style: { color: '#3b82f6', radius: 4 },
  },
  {
    id: 'file-nodes',
    label: 'Files (top-level calls)',
    enabled: true,
    match: (n) => n.kind === 'FILE',
    forces: { charge: -120, collideRadius: 10 },
    style: { color: '#6b7280', radius: 8 },
  },
];

export const defaultEdgeRules: EdgeForceRule[] = [
  {
    id: 'call-same-file',
    label: 'Same-File Calls',
    enabled: true,
    match: (e) => e.type === 'call' && (e as CallEdge).callScope === 'same-file',
    forces: { linkDistance: 30, linkStrength: 0.8 },
    style: { color: '#9ca3af', width: 1 },
  },
  {
    id: 'call-cross-file',
    label: 'Cross-File Calls',
    enabled: true,
    match: (e) => e.type === 'call' && (e as CallEdge).callScope === 'cross-file',
    forces: { linkDistance: 50, linkStrength: 0.6 },
    style: { color: '#9ca3af', width: 1.5 },
  },
  {
    id: 'call-external',
    label: 'External Calls',
    enabled: true,
    match: (e) => e.type === 'call' && (e as CallEdge).callScope === 'external',
    forces: { linkDistance: 100, linkStrength: 0.3 },
    style: { color: '#9ca3af', width: 1 },
  },
  {
    id: 'uses-type-ref',
    label: 'Type References',
    enabled: true,
    match: (e) => e.type === 'uses' && (e as UsesEdge).usageKind === 'type-reference',
    forces: { linkDistance: 100, linkStrength: 0.5 },
    style: { color: '#9ca3af', width: 1 },
  },
  {
    id: 'uses-extends',
    label: 'Extends',
    enabled: true,
    match: (e) => e.type === 'uses' && (e as UsesEdge).usageKind === 'extends',
    forces: { linkDistance: 100, linkStrength: 0.4 },
    style: { color: '#9ca3af', width: 1.5 },
  },
  {
    id: 'uses-implements',
    label: 'Implements',
    enabled: true,
    match: (e) => e.type === 'uses' && (e as UsesEdge).usageKind === 'implements',
    forces: { linkDistance: 100, linkStrength: 0.4 },
    style: { color: '#9ca3af', width: 1.5 },
  },
];
