import { NodeForceRule, EdgeForceRule, CallEdge, ContainsEdge, UsesEdge } from './types';

export const defaultNodeRules: NodeForceRule[] = [
  {
    id: 'folder-nodes',
    label: 'Folders',
    enabled: true,
    match: (n) => n.kind === 'FOLDER',
    forces: { charge: -400, collideRadius: 30, zone: 'center' },
    style: { color: '#d1d5db', radius: 3 },
  },
  {
    id: 'file-tsx',
    label: 'TSX Files',
    enabled: true,
    match: (n) => n.kind === 'FILE' && n.fileType === 'tsx',
    forces: { charge: -200, collideRadius: 15 },
    style: { color: '#9ca3af', radius: 5 },
  },
  {
    id: 'file-ts',
    label: 'TS Files',
    enabled: true,
    match: (n) => n.kind === 'FILE' && n.fileType === 'ts',
    forces: { charge: -200, collideRadius: 15 },
    style: { color: '#9ca3af', radius: 5 },
  },
  {
    id: 'function-nodes',
    label: 'Functions',
    enabled: true,
    match: (n) => n.kind === 'FUNCTION',
    forces: { charge: -100, collideRadius: 8 },
    style: { color: '#10b981', radius: 5 },
  },
  {
    id: 'class-nodes',
    label: 'Classes',
    enabled: true,
    match: (n) => n.kind === 'CLASS',
    forces: { charge: -300, collideRadius: 20 },
    style: { color: '#f59e0b', radius: 10 },
  },
  {
    id: 'interface-nodes',
    label: 'Interfaces',
    enabled: true,
    match: (n) => n.kind === 'INTERFACE',
    forces: { charge: -150, collideRadius: 12 },
    style: { color: '#8b5cf6', radius: 7 },
  },
  {
    id: 'import-nodes',
    label: 'Imports',
    enabled: true,
    match: (n) => n.kind === 'IMPORT',
    forces: { charge: -80, collideRadius: 6 },
    style: { color: '#3b82f6', radius: 4 },
  },
];

export const defaultEdgeRules: EdgeForceRule[] = [
  {
    id: 'folder-folder-contains',
    label: 'Folder → Folder',
    enabled: true,
    match: (e) => e.type === 'contains' && (e as ContainsEdge).containsScope === 'folder' && e.target.startsWith('folder:'),
    forces: { linkDistance: 10, linkStrength: 1.0 },
    style: { color: '#d1d5db', width: 0.5 },
  },
  {
    id: 'folder-file-contains',
    label: 'Folder → File',
    enabled: true,
    match: (e) => e.type === 'contains' && (e as ContainsEdge).containsScope === 'folder' && e.target.startsWith('file:'),
    forces: { linkDistance: 20, linkStrength: 0.6 },
    style: { color: '#d1d5db', width: 0.5 },
  },
  {
    id: 'file-contains-edges',
    label: 'File Contains',
    enabled: true,
    match: (e) => e.type === 'contains' && (e as ContainsEdge).containsScope === 'file',
    forces: { linkDistance: 5, linkStrength: 1.0 },
    style: { color: '#9ca3af', width: 1 },
  },
  {
    id: 'call-same-file',
    label: 'Same-File Calls',
    enabled: true,
    match: (e) => e.type === 'call' && (e as CallEdge).callScope === 'same-file',
    forces: { linkDistance: 30, linkStrength: 1.0 },
    style: { color: '#374151', width: 1 },
  },
  {
    id: 'call-cross-file',
    label: 'Cross-File Calls',
    enabled: true,
    match: (e) => e.type === 'call' && (e as CallEdge).callScope === 'cross-file',
    forces: { linkDistance: 150, linkStrength: 0.3 },
    style: { color: '#10b981', width: 1.5 },
  },
  {
    id: 'call-external',
    label: 'External Calls',
    enabled: true,
    match: (e) => e.type === 'call' && (e as CallEdge).callScope === 'external',
    forces: { linkDistance: 100, linkStrength: 0.3 },
    style: { color: '#3b82f6', width: 1 },
  },
  {
    id: 'uses-type-ref',
    label: 'Type References',
    enabled: true,
    match: (e) => e.type === 'uses' && (e as UsesEdge).usageKind === 'type-reference',
    forces: { linkDistance: 160, linkStrength: 0.2 },
    style: { color: '#8b5cf6', width: 1 },
  },
  {
    id: 'uses-extends',
    label: 'Extends',
    enabled: true,
    match: (e) => e.type === 'uses' && (e as UsesEdge).usageKind === 'extends',
    forces: { linkDistance: 120, linkStrength: 0.4 },
    style: { color: '#f59e0b', width: 1.5 },
  },
  {
    id: 'uses-implements',
    label: 'Implements',
    enabled: true,
    match: (e) => e.type === 'uses' && (e as UsesEdge).usageKind === 'implements',
    forces: { linkDistance: 120, linkStrength: 0.4 },
    style: { color: '#ec4899', width: 1.5 },
  },
];
