import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Git Explorer",
  description: "Generated by create next app",
};

/**
 * Root layout component that sets up font families and the HTML document
 * shell for all pages.
 *
 * @remarks
 * Loads Geist Sans and Geist Mono fonts via `next/font/google` and applies
 * them as CSS variables. All page content renders inside this layout.
 *
 * @param children - Page content rendered by the Next.js router.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
